version: 2.1
# Orbs - Reusable packages for use.
orbs:
  node: circleci/node@5.2.0
  docker: circleci/docker@2.6.0
  # heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@2.1.0

# Jobs - Set of instructions / Functions.
jobs:
  build: # Job name.
    docker: # Environment.
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker: # Environment.
      - image: cimg/node:20.12.2
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

  scan:
    docker:
      - image: cimg/node:20.12.2
    environment: # The environment allows us to create an environment for the job and allows us to create custom environment variables.
      IMAGE_NAME: nhkhai/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME . # $IMAGE_NAME gets the value from the environment we created above.
      - snyk/scan: # This triggers the Snyk scan using the preconfigured SNYK_TOKEN environmental variable.
          docker-image-name: $IMAGE_NAME
          fail-on-issues: false
          severity-threshold: high

  publish: # Also known as the build-and-push.
    executor: docker/docker # Define the execution environment in which the steps of a job will run.
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: # Build the image.
          image: nhkhai/education-space
          # Mini Activity #3 - Add a tag called v1.0.1 and push the tag in docker hub.
          # tag: v1.0.1
          tag: latest # Consider setting this dynamically based on the tag using env vars or CircleCI parameters.
          # tag: ${CIRCLE_TAG:-latest}  # Use the tag name if triggered by a tag, otherwise use 'latest'.
      - docker/push: # Pushes the image to the specified account in the environment variables.
          image: nhkhai/education-space
          # tag: v1.0.1
          tag: latest # Consider setting this dynamically based on the tag using env vars or CircleCI parameters.
          # tag: ${CIRCLE_TAG:-latest}  # Use the tag name if triggered by a tag, otherwise use 'latest'.

  # deploy:
  #   docker:
  #       - image: cimg/node:20.12.2
  #   steps:
  #       - setup_remote_docker
  #       - heroku/install
  #       - checkout
  #       - run:
  #           name: Heroku Container Push
  #           command: |
  #               heroku container:login
  #               heroku container:push web -a nhkhai-node-app-for-devops
  #               heroku container:release web -a nhkhai-node-app-for-devops
  deploy:
    docker:
      # - image: cimg/deploy:2024.03
      - image: cimg/base:current-22.04
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Render Deploy Hook
          command: |
            curl "$RENDER_DEPLOY_HOOK_URL"

# Workflow - Defines what sequence will the jobs run.
workflows:
  simple_workflow: # Workflow name.
    jobs:
      - build
      # - build:
      #     filters:
      #       branches:
      #         only:
      #           - main
      #         ignore:
      #           - release
      - test:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - main
          #     ignore:
          #       - release
      # The scan job.
      - scan:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - main
          #     ignore:
          #       - release
      # Mini Activity #2 - How to make the publish job execute after the test job?
      - publish:
          requires:
            - test
          filters:
            # tags:
            #   only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Ensure this job runs only for semantically versioned tags. This regex pattern matches semantic versioning tags (e.g., v1.0.0, v2.1.3).
            branches:
              only:
                - release
      - deploy:
          requires:
            - publish
          filters:
            # tags:
            #   only: /^v[0-9]+\.[0-9]+\.[0-9]+$/ # Ensure this job runs only for semantically versioned tags. This regex pattern matches semantic versioning tags (e.g., v1.0.0, v2.1.3).
            branches:
              only:
                - release
