version: 2.1
# Orbs - Reusable packages for use.
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# Jobs - Set of instructions / Functions.
jobs:
  build: # Job name.
    docker: # Environment.
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker: # Environment.
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish: # Also known as the build-and-push.
    executor: docker/docker # Define the execution environment in which the steps of a job will run.
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: # Build the image.
          image: nhkhai/education-space
          tag: latest
      - docker/push: # Pushes the image to the specified account in the environment variables.
          image: nhkhai/education-space
          tag: latest
# Workflow - Defines what sequence will the jobs run.
workflows:
  simple_workflow: # Workflow name.
    jobs:
      - build
      - test:
          requires:
            - build
      # Mini activity #2 - How to make the publish job execute after the test job?
      - publish:
          requires:
            - test
