version: 2.1
# Orbs - Reusable packages for use.
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  # heroku: circleci/heroku@2.0.0
# Jobs - Set of instructions / Functions.
jobs:
  build: # Job name.
    docker: # Environment.
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker: # Environment.
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish: # Also known as the build-and-push.
    executor: docker/docker # Define the execution environment in which the steps of a job will run.
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build: # Build the image.
          image: nhkhai/education-space
          # Mini Activity #3 - Add a tag called v1.0.1 and push the tag in docker hub.
          tag: v1.0.1
      - docker/push: # Pushes the image to the specified account in the environment variables.
          image: nhkhai/education-space
          tag: v1.0.1
  # deploy:
  #   docker:
  #       - image: cimg/node:16.10
  #   steps:
  #       - setup_remote_docker
  #       - heroku/install
  #       - checkout
  #       - run:
  #           name: Heroku Container Push
  #           command: |
  #               heroku container:login
  #               heroku container:push web -a nhkhai-node-app-for-devops
  #               heroku container:release web -a nhkhai-node-app-for-devops
  deploy:
    docker:
      # - image: cimg/deploy:2024.03
      - image: cimg/base:current-22.04
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Render Deploy Hook
          command: |
            curl "$RENDER_DEPLOY_HOOK_URL"
# Workflow - Defines what sequence will the jobs run.
workflows:
  simple_workflow: # Workflow name.
    jobs:
      - build
      - test:
          requires:
            - build
      # Mini Activity #2 - How to make the publish job execute after the test job?
      - publish:
          requires:
            - test
      - deploy:
          requires:
            - publish
